"""Add audit logs and notice drafts

Revision ID: 6a7dfde6e5d6
Revises: cdde5919f8c6
Create Date: 2026-03-11 00:24:55.026698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a7dfde6e5d6'
down_revision: Union[str, Sequence[str], None] = 'cdde5919f8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'case_manager', 'advocate', 'staff', name='user_role', schema='app'), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'locked', 'disabled', name='user_status', schema='app'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username'),
    schema='app'
    )
    op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    op.create_table('case_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'validated', 'imported', 'failed', name='import_status', schema='app'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_code', sa.String(), nullable=False),
    sa.Column('ref_no', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('agreement_no', sa.String(), nullable=True),
    sa.Column('agreement_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_advocate_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('allocated_at', sa.Date(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('branch_code', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('repossession_status', sa.String(), nullable=True),
    sa.Column('dpd', sa.String(), nullable=True),
    sa.Column('allocation_pos', sa.String(), nullable=True),
    sa.Column('claim_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('claim_date', sa.Date(), nullable=True),
    sa.Column('amount_financed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('finance_charge', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('agreement_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('award_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('award_amount_words', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('engine_no', sa.String(), nullable=True),
    sa.Column('chassis_no', sa.String(), nullable=True),
    sa.Column('reg_no', sa.String(), nullable=True),
    sa.Column('first_emi_date', sa.Date(), nullable=True),
    sa.Column('last_emi_date', sa.Date(), nullable=True),
    sa.Column('tenure', sa.Integer(), nullable=True),
    sa.Column('sec_17_applied', sa.String(), nullable=True),
    sa.Column('sec_17_applied_date', sa.Date(), nullable=True),
    sa.Column('sec_17_received_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_advocate_id'], ['app.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['app.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_no'),
    sa.UniqueConstraint('case_code'),
    schema='app'
    )
    op.create_index(op.f('ix_app_cases_assigned_advocate_id'), 'cases', ['assigned_advocate_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_cases_ref_no'), 'cases', ['ref_no'], unique=False, schema='app')
    op.create_index(op.f('ix_app_cases_status'), 'cases', ['status'], unique=False, schema='app')
    op.create_table('case_arbitration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('arbitrator_name', sa.String(), nullable=True),
    sa.Column('arbitrator_phone', sa.String(), nullable=True),
    sa.Column('arbitrator_email', sa.String(), nullable=True),
    sa.Column('arbitrator_address', sa.String(), nullable=True),
    sa.Column('acceptance_date', sa.Date(), nullable=True),
    sa.Column('arb_case_no', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    schema='app'
    )
    op.create_table('case_import_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', name='import_row_status', schema='app'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['app.case_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_case_import_rows_import_id'), 'case_import_rows', ['import_id'], unique=False, schema='app')
    op.create_table('case_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('milestone_type', sa.Enum('FIRST_MEETING', 'SECOND_MEETING', 'THIRD_MEETING_EXPARTE', 'EVIDENCE_ARGUMENT', 'AWARD_DATE', 'STAMP_PURCHASE_DATE', name='milestone_type', schema='app'), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_case_milestones_case_id'), 'case_milestones', ['case_id'], unique=False, schema='app')
    op.create_table('case_parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('party_type', sa.Enum('applicant', 'co_applicant', 'guarantor', name='party_type', schema='app'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('residence_address_2', sa.String(), nullable=True),
    sa.Column('residence_address_3', sa.String(), nullable=True),
    sa.Column('office_address_1', sa.String(), nullable=True),
    sa.Column('office_address_2', sa.String(), nullable=True),
    sa.Column('office_address_3', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('phone_2', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_case_parties_case_id'), 'case_parties', ['case_id'], unique=False, schema='app')
    op.create_table('case_rules_state',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('notice_count', sa.Integer(), nullable=False),
    sa.Column('closure_enabled', sa.Boolean(), nullable=False),
    sa.Column('closure_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id'),
    schema='app'
    )
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meet_provider', sa.Enum('google_meet', name='meet_provider', schema='app'), nullable=False),
    sa.Column('meet_url', sa.String(), nullable=True),
    sa.Column('portal_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='meeting_status', schema='app'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['app.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_meetings_case_id'), 'meetings', ['case_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_meetings_scheduled_at'), 'meetings', ['scheduled_at'], unique=False, schema='app')
    op.create_table('notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('notice_no', sa.Integer(), nullable=False),
    sa.Column('notice_type', sa.String(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'failed', name='notice_status', schema='app'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['app.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_notices_case_id'), 'notices', ['case_id'], unique=False, schema='app')
    op.create_table('otp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('victim_contact', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token'),
    schema='app'
    )
    op.create_index(op.f('ix_app_otp_sessions_case_id'), 'otp_sessions', ['case_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_otp_sessions_expires_at'), 'otp_sessions', ['expires_at'], unique=False, schema='app')
    op.create_table('victim_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_victim_accounts_case_id'), 'victim_accounts', ['case_id'], unique=False, schema='app')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('internal', 'victim', 'system', name='actor_type', schema='app'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_victim_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_victim_id'], ['app.victim_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='app')
    op.create_index(op.f('ix_app_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False, schema='app')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_victim_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('internal', 'victim', name='doc_source', schema='app'), nullable=False),
    sa.Column('category', sa.Enum('ID_PROOF', 'LOAN_DOC', 'NOTICE', 'OTHER', name='doc_category', schema='app'), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['app.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_victim_id'], ['app.victim_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_documents_case_id'), 'documents', ['case_id'], unique=False, schema='app')
    op.create_table('notice_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'whatsapp', 'email', name='delivery_channel', schema='app'), nullable=False),
    sa.Column('to_address', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'read', 'failed', name='delivery_status', schema='app'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['app.notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_notice_deliveries_notice_id'), 'notice_deliveries', ['notice_id'], unique=False, schema='app')
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_downloadable_internal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['app.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['app.meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_recordings_case_id'), 'recordings', ['case_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_recordings_meeting_id'), 'recordings', ['meeting_id'], unique=False, schema='app')
    op.create_table('document_access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('viewer_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['app.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['app.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_document_access_logs_document_id'), 'document_access_logs', ['document_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_document_access_logs_viewer_user_id'), 'document_access_logs', ['viewer_user_id'], unique=False, schema='app')
    op.create_table('notice_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['app.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notice_id'], ['app.notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_notice_attachments_document_id'), 'notice_attachments', ['document_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_notice_attachments_notice_id'), 'notice_attachments', ['notice_id'], unique=False, schema='app')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_case_imports_created_at'), table_name='case_imports')
    op.drop_index(op.f('ix_case_imports_status'), table_name='case_imports')
    op.drop_table('case_imports')
    op.drop_index(op.f('ix_recordings_case_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_meeting_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_case_arbitration_case_id'), table_name='case_arbitration')
    op.drop_table('case_arbitration')
    op.drop_index(op.f('ix_cases_agreement_no'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_advocate_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_ref_no'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_table('cases')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_notice_deliveries_notice_id'), table_name='notice_deliveries')
    op.drop_index(op.f('ix_notice_deliveries_status'), table_name='notice_deliveries')
    op.drop_table('notice_deliveries')
    op.drop_index(op.f('ix_document_access_logs_at'), table_name='document_access_logs')
    op.drop_index(op.f('ix_document_access_logs_document_id'), table_name='document_access_logs')
    op.drop_index(op.f('ix_document_access_logs_viewer_user_id'), table_name='document_access_logs')
    op.drop_table('document_access_logs')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_meetings_case_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_scheduled_at'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_victim_accounts_case_id'), table_name='victim_accounts')
    op.drop_table('victim_accounts')
    op.drop_index(op.f('ix_case_milestones_case_id'), table_name='case_milestones')
    op.drop_index(op.f('ix_case_milestones_milestone_type'), table_name='case_milestones')
    op.drop_table('case_milestones')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_case_parties_case_id'), table_name='case_parties')
    op.drop_index(op.f('ix_case_parties_party_type'), table_name='case_parties')
    op.drop_table('case_parties')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('case_rules_state')
    op.drop_index(op.f('ix_notices_case_id'), table_name='notices')
    op.drop_index(op.f('ix_notices_status'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_case_import_rows_import_id'), table_name='case_import_rows')
    op.drop_index(op.f('ix_case_import_rows_status'), table_name='case_import_rows')
    op.drop_table('case_import_rows')
    op.drop_index(op.f('ix_otp_sessions_case_id'), table_name='otp_sessions')
    op.drop_index(op.f('ix_otp_sessions_expires_at'), table_name='otp_sessions')
    op.drop_table('otp_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('victim_contact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('session_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('otp_sessions_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_sessions_pkey')),
    sa.UniqueConstraint('session_token', name=op.f('otp_sessions_session_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_otp_sessions_expires_at'), 'otp_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_sessions_case_id'), 'otp_sessions', ['case_id'], unique=False)
    op.create_table('case_import_rows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('import_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('row_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('case_import_rows_case_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['case_imports.id'], name=op.f('case_import_rows_import_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('case_import_rows_pkey'))
    )
    op.create_index(op.f('ix_case_import_rows_status'), 'case_import_rows', ['status'], unique=False)
    op.create_index(op.f('ix_case_import_rows_import_id'), 'case_import_rows', ['import_id'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notice_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notice_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('notices_case_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('notices_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('notices_pkey'))
    )
    op.create_index(op.f('ix_notices_status'), 'notices', ['status'], unique=False)
    op.create_index(op.f('ix_notices_case_id'), 'notices', ['case_id'], unique=False)
    op.create_table('case_rules_state',
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notice_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('closure_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('closure_enabled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('case_rules_state_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', name=op.f('case_rules_state_pkey'))
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by_victim_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('storage_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('checksum_sha256', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('documents_case_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('documents_uploaded_by_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_victim_id'], ['victim_accounts.id'], name=op.f('documents_uploaded_by_victim_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_table('case_parties',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('party_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('father_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('case_parties_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('case_parties_pkey'))
    )
    op.create_index(op.f('ix_case_parties_party_type'), 'case_parties', ['party_type'], unique=False)
    op.create_index(op.f('ix_case_parties_case_id'), 'case_parties', ['case_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('permission_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_key'], ['permissions.key'], name=op.f('role_permissions_permission_key_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_key', 'permission_key', name=op.f('role_permissions_pkey'))
    )
    op.create_table('case_milestones',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('milestone_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('planned_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('case_milestones_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('case_milestones_pkey'))
    )
    op.create_index(op.f('ix_case_milestones_milestone_type'), 'case_milestones', ['milestone_type'], unique=False)
    op.create_index(op.f('ix_case_milestones_case_id'), 'case_milestones', ['case_id'], unique=False)
    op.create_table('victim_accounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('victim_accounts_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('victim_accounts_pkey'))
    )
    op.create_index(op.f('ix_victim_accounts_case_id'), 'victim_accounts', ['case_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('meet_provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meet_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('portal_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('meetings_case_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('meetings_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('meetings_pkey'))
    )
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_scheduled_at'), 'meetings', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_meetings_case_id'), 'meetings', ['case_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actor_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_victim_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('audit_logs_actor_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_victim_id'], ['victim_accounts.id'], name=op.f('audit_logs_actor_victim_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('permissions_pkey')),
    sa.UniqueConstraint('key', name=op.f('permissions_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('document_access_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('viewer_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_access_logs_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], name=op.f('document_access_logs_viewer_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_access_logs_pkey'))
    )
    op.create_index(op.f('ix_document_access_logs_viewer_user_id'), 'document_access_logs', ['viewer_user_id'], unique=False)
    op.create_index(op.f('ix_document_access_logs_document_id'), 'document_access_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_access_logs_at'), 'document_access_logs', ['at'], unique=False)
    op.create_table('notice_deliveries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider_message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], name=op.f('notice_deliveries_notice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notice_deliveries_pkey'))
    )
    op.create_index(op.f('ix_notice_deliveries_status'), 'notice_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_notice_deliveries_notice_id'), 'notice_deliveries', ['notice_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_allowed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_key'], ['permissions.key'], name=op.f('user_permissions_permission_key_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_permissions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_key', name=op.f('user_permissions_pkey'))
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ref_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agreement_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agreement_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assigned_advocate_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('allocated_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('claim_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('claim_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('amount_financed', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('finance_charge', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('agreement_value', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('award_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('award_amount_words', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('make', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('engine_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chassis_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reg_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_advocate_id'], ['users.id'], name=op.f('cases_assigned_advocate_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('cases_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('cases_pkey')),
    sa.UniqueConstraint('case_code', name=op.f('cases_case_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_ref_no'), 'cases', ['ref_no'], unique=False)
    op.create_index(op.f('ix_cases_assigned_advocate_id'), 'cases', ['assigned_advocate_id'], unique=False)
    op.create_index(op.f('ix_cases_agreement_no'), 'cases', ['agreement_no'], unique=True)
    op.create_table('case_arbitration',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('institution_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arbitrator_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arbitrator_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arbitrator_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arbitrator_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('acceptance_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('arb_case_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('case_arbitration_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('case_arbitration_pkey'))
    )
    op.create_index(op.f('ix_case_arbitration_case_id'), 'case_arbitration', ['case_id'], unique=True)
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('checksum_sha256', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_downloadable_internal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('recordings_case_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('recordings_meeting_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('recordings_uploaded_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('recordings_pkey'))
    )
    op.create_index(op.f('ix_recordings_meeting_id'), 'recordings', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_recordings_case_id'), 'recordings', ['case_id'], unique=False)
    op.create_table('case_imports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_rows', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success_rows', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_rows', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('case_imports_uploaded_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('case_imports_pkey'))
    )
    op.create_index(op.f('ix_case_imports_status'), 'case_imports', ['status'], unique=False)
    op.create_index(op.f('ix_case_imports_created_at'), 'case_imports', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('employee_id', name=op.f('users_employee_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone', name=op.f('users_phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_app_notice_attachments_notice_id'), table_name='notice_attachments', schema='app')
    op.drop_index(op.f('ix_app_notice_attachments_document_id'), table_name='notice_attachments', schema='app')
    op.drop_table('notice_attachments', schema='app')
    op.drop_index(op.f('ix_app_document_access_logs_viewer_user_id'), table_name='document_access_logs', schema='app')
    op.drop_index(op.f('ix_app_document_access_logs_document_id'), table_name='document_access_logs', schema='app')
    op.drop_table('document_access_logs', schema='app')
    op.drop_index(op.f('ix_app_recordings_meeting_id'), table_name='recordings', schema='app')
    op.drop_index(op.f('ix_app_recordings_case_id'), table_name='recordings', schema='app')
    op.drop_table('recordings', schema='app')
    op.drop_index(op.f('ix_app_notice_deliveries_notice_id'), table_name='notice_deliveries', schema='app')
    op.drop_table('notice_deliveries', schema='app')
    op.drop_index(op.f('ix_app_documents_case_id'), table_name='documents', schema='app')
    op.drop_table('documents', schema='app')
    op.drop_index(op.f('ix_app_audit_logs_created_at'), table_name='audit_logs', schema='app')
    op.drop_index(op.f('ix_app_audit_logs_action'), table_name='audit_logs', schema='app')
    op.drop_table('audit_logs', schema='app')
    op.drop_index(op.f('ix_app_victim_accounts_case_id'), table_name='victim_accounts', schema='app')
    op.drop_table('victim_accounts', schema='app')
    op.drop_index(op.f('ix_app_otp_sessions_expires_at'), table_name='otp_sessions', schema='app')
    op.drop_index(op.f('ix_app_otp_sessions_case_id'), table_name='otp_sessions', schema='app')
    op.drop_table('otp_sessions', schema='app')
    op.drop_index(op.f('ix_app_notices_case_id'), table_name='notices', schema='app')
    op.drop_table('notices', schema='app')
    op.drop_index(op.f('ix_app_meetings_scheduled_at'), table_name='meetings', schema='app')
    op.drop_index(op.f('ix_app_meetings_case_id'), table_name='meetings', schema='app')
    op.drop_table('meetings', schema='app')
    op.drop_table('case_rules_state', schema='app')
    op.drop_index(op.f('ix_app_case_parties_case_id'), table_name='case_parties', schema='app')
    op.drop_table('case_parties', schema='app')
    op.drop_index(op.f('ix_app_case_milestones_case_id'), table_name='case_milestones', schema='app')
    op.drop_table('case_milestones', schema='app')
    op.drop_index(op.f('ix_app_case_import_rows_import_id'), table_name='case_import_rows', schema='app')
    op.drop_table('case_import_rows', schema='app')
    op.drop_table('case_arbitration', schema='app')
    op.drop_index(op.f('ix_app_cases_status'), table_name='cases', schema='app')
    op.drop_index(op.f('ix_app_cases_ref_no'), table_name='cases', schema='app')
    op.drop_index(op.f('ix_app_cases_assigned_advocate_id'), table_name='cases', schema='app')
    op.drop_table('cases', schema='app')
    op.drop_table('case_imports', schema='app')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    op.drop_table('users', schema='app')
    # ### end Alembic commands ###
